# Generated by Django 4.0 on 2021-12-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='primary_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('sku_name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('manufacturer_name', models.CharField(max_length=350)),
                ('salt_name', models.CharField(max_length=100)),
                ('drug_form', models.CharField(max_length=50)),
                ('Pack_size', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('product_banned_flag', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('price_per_unit', models.FloatField()),
            ],
            options={
                'db_table': 'primary_medicine_details',
                'managed': True,
            },
        ),
    ]
