# Generated by Django 4.0 on 2021-12-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_dir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primary_model',
            old_name='Pack_size',
            new_name='pack_size',
        ),
    ]
