# Generated by Django 4.0 on 2021-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dir', '0002_rename_pack_size_primary_model_pack_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary_model',
            name='drug_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='pack_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='price_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='product_banned_flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='salt_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='sku_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='sku_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='strength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
