# Generated by Django 4.0 on 2021-12-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dir', '0004_alter_primary_model_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary_model',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='sku_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
