# Generated by Django 4.0 on 2021-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dir', '0005_alter_primary_model_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary_model',
            name='drug_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='pack_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='product_banned_flag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='salt_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='primary_model',
            name='strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
