# Generated by Django 4.0 on 2021-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dir', '0007_alter_primary_model_salt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary_model',
            name='strength',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
