# Generated by Django 3.1.4 on 2021-12-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_dir', '0008_alter_primary_model_strength'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primary_model',
            options={},
        ),
    ]
