# Generated by Django 3.1.4 on 2021-12-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_dir', '0009_auto_20211214_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('secname', models.CharField(max_length=50)),
            ],
        ),
    ]
